const { BeezleClient } = require("beezle.js");
const client = new BeezleClient(
	"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25uZWN0ZWRfYWNjb3VudHMiOnsic3BvdGlmeSI6eyJhY2Nlc3NfdG9rZW4iOiIiLCJyZWZyZXNoX3Rva2VuIjoiIn19LCJzdXBwb3J0ZXIiOmZhbHNlLCJtaWxlc3RvbmVzIjpbXSwic3RhdHVzIjoib25saW5lIiwiYm90X2FjY291bnQiOmZhbHNlLCJfaWQiOiI2NGExYzlhN2NhZDY3NTRjYzA4ZTA1NGYiLCJoYW5kbGUiOiJrb2tpMiIsImRpc3BsYXlOYW1lIjoiREVNT01BTiIsImVtYWlsIjoiYWxtYXJhNzdAbWFpbC5ydSIsInBhc3N3b3JkIjoiJDJiJDEwJFZ4REJhNUZCTnhZUW1HTmhHNGVrMU9OcUhzWmh0c3poMlJ0Z1JkZ2UyaUNIa0NWWkZRd0VTIiwiYmlvIjoiPHA-SSBBTSBERU1PTUFOTiE8L3A-IiwiYXZhdGFyIjoiaHR0cHM6Ly9tZWRpYS5kaXNjb3JkYXBwLm5ldC9hdHRhY2htZW50cy8xMTIzNjI0MTUwMjI1OTIwMDYwLzExMjUxMzk0OTI0NzEzMTY3NDAvNzZjZThjODljMzZiMDBkNGM0OGEwMTdkZjZjZTY5ZTAuanBlZyIsImJhbm5lciI6Imh0dHBzOi8vbWVkaWEuZGlzY29yZGFwcC5uZXQvYXR0YWNobWVudHMvMTEyMzYyNDE1MDIyNTkyMDA2MC8xMTI1MTM5NTI4MTMxMjg5MDg4L2YzZTc0NWUwOWQzMmFiNTZmYWExZjQxMGY4OTZiMzA3LmpwZWciLCJtb2RlcmF0b3IiOmZhbHNlLCJvd25lciI6ZmFsc2UsImZvbGxvd2luZyI6WyJiZWV6bGUiLCJrb2tpIl0sImZvbGxvd2VycyI6WyJrb2tpIl0sIl9fdiI6MTEsImJvb2ttYXJrcyI6W10sIm5vdGlmaWNhdGlvbnMiOltdLCJhY3RpdmUiOnRydWUsInByaXZhdGUiOmZhbHNlLCJidWdfaHVudGVyIjpmYWxzZSwidmVyaWZpZWQiOmZhbHNlLCJpYXQiOjE2ODk0Mjg0MzR9.R0YFQAr83Kj5uXnhAZqV0ahG-xwGfdXXPwZW1pYmQbA"
);

async function init() {
	await client.setUser();
	client.onPost("post", post => {
		if (post.data.content.includes("!ping")) {
			client.reply(post.data.postID, "Pong!");
		}
	});
}
init();
